#My helixrc
 
# theme = "doom_acario_dark"
# theme = "ayu_evolve"
# theme = "ataraxia"
theme = "dark-synthwave"
# theme = "curzon"
# theme = "gruber-darker"
# theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
auto-save = true
auto-pairs = true
mouse = true
cursorline = true
true-color = true
clipboard-provider = "termcode"
bufferline = "always"
scrolloff = 0

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 3

[editor.cursor-shape]
insert="block"
normal="block"
select="block"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
# j = { k = "normal_mode" }

[keys.normal]
"C-j" = ":pipe tr 'a-z' 'A-Z'"
"C-k" = ":pipe tr 'A-Z' 'a-z'"
